// Dummy data for testing filterNonWaterTempRows function
// Based on links provided

export const mockWaterTempRow1 = {
  data: {
    ActivityDepthHeightMeasure: "",
    ActivityDepthHeightUnit: "",
    ActivityEndDate: "",
    ActivityEndTime: "",
    ActivityMediaName: "Surface Water",
    ActivityStartDate: "2005-06-23",
    ActivityStartTime: "",
    ActivityType: "Field Msr/Obs",
    AnalysisStartDate: "",
    AnalysisStartTime: "",
    AnalysisStartTimeZone: "",
    CharacteristicName: "Temperature, water",
    DatasetName: "RivTemp--INRS",
    LaboratoryName: "",
    LaboratorySampleID: "",
    MethodSpeciation: "",
    MonitoringLocationHorizontalAccuracyMeasure: "",
    MonitoringLocationHorizontalAccuracyUnit: "",
    MonitoringLocationHorizontalCoordinateReferenceSystem: "WGS84",
    MonitoringLocationID: "RivTemp-Qc-16-75",
    MonitoringLocationLatitude: "48.26451",
    MonitoringLocationLongitude: "-69.86347",
    MonitoringLocationName:
      "Froid NE P - Riv. Ste-Marguerite Nord-Est (Saguenay)",
    MonitoringLocationType: "River/Stream",
    MonitoringLocationVerticalMeasure: "",
    MonitoringLocationVerticalUnit: "",
    ResultAnalyticalMethodContext: "",
    ResultAnalyticalMethodID: "",
    ResultAnalyticalMethodName: "",
    ResultComment: "Tmoy journalier/daily Tmean",
    ResultDetectionCondition: "",
    ResultDetectionQuantitationLimitMeasure: "",
    ResultDetectionQuantitationLimitType: "",
    ResultDetectionQuantitationLimitUnit: "",
    ResultSampleFraction: "",
    ResultStatusID: "",
    ResultUnit: "deg C",
    ResultValue: "14.6",
    ResultValueType: "Calculated",
    SampleCollectionEquipmentName: "",
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockWaterTempRow2 = {
  data: {
    ActivityDepthHeightMeasure: "",
    ActivityDepthHeightUnit: "",
    ActivityEndDate: "",
    ActivityEndTime: "",
    ActivityMediaName: "Surface Water",
    ActivityStartDate: "2005-06-24",
    ActivityStartTime: "",
    ActivityType: "Field Msr/Obs",
    AnalysisStartDate: "",
    AnalysisStartTime: "",
    AnalysisStartTimeZone: "",
    CharacteristicName: "Temperature, water",
    DatasetName: "RivTemp--INRS",
    LaboratoryName: "",
    LaboratorySampleID: "",
    MethodSpeciation: "",
    MonitoringLocationHorizontalAccuracyMeasure: "",
    MonitoringLocationHorizontalAccuracyUnit: "",
    MonitoringLocationHorizontalCoordinateReferenceSystem: "WGS84",
    MonitoringLocationID: "RivTemp-Qc-16-75", // Same location as row1
    MonitoringLocationLatitude: "48.26451",
    MonitoringLocationLongitude: "-69.86347",
    MonitoringLocationName:
      "Froid NE P - Riv. Ste-Marguerite Nord-Est (Saguenay)",
    MonitoringLocationType: "River/Stream",
    MonitoringLocationVerticalMeasure: "",
    MonitoringLocationVerticalUnit: "",
    ResultAnalyticalMethodContext: "",
    ResultAnalyticalMethodID: "",
    ResultAnalyticalMethodName: "",
    ResultComment: "Tmoy journalier/daily Tmean",
    ResultDetectionCondition: "",
    ResultDetectionQuantitationLimitMeasure: "",
    ResultDetectionQuantitationLimitType: "",
    ResultDetectionQuantitationLimitUnit: "",
    ResultSampleFraction: "",
    ResultStatusID: "",
    ResultUnit: "deg C",
    ResultValue: "16.2",
    ResultValueType: "Calculated",
    SampleCollectionEquipmentName: "",
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockWaterTempRowDifferentLocation = {
  data: {
    ActivityDepthHeightMeasure: "",
    ActivityDepthHeightUnit: "",
    ActivityEndDate: "",
    ActivityEndTime: "",
    ActivityMediaName: "Surface Water",
    ActivityStartDate: "2005-06-23",
    ActivityStartTime: "",
    ActivityType: "Field Msr/Obs",
    AnalysisStartDate: "",
    AnalysisStartTime: "",
    AnalysisStartTimeZone: "",
    CharacteristicName: "Temperature, water",
    DatasetName: "RivTemp--INRS",
    LaboratoryName: "",
    LaboratorySampleID: "",
    MethodSpeciation: "",
    MonitoringLocationHorizontalAccuracyMeasure: "",
    MonitoringLocationHorizontalAccuracyUnit: "",
    MonitoringLocationHorizontalCoordinateReferenceSystem: "WGS84",
    MonitoringLocationID: "RivTemp-Qc-17-80", // Different location
    MonitoringLocationLatitude: "47.12345",
    MonitoringLocationLongitude: "-68.54321",
    MonitoringLocationName: "Different River Location",
    MonitoringLocationType: "River/Stream",
    MonitoringLocationVerticalMeasure: "",
    MonitoringLocationVerticalUnit: "",
    ResultAnalyticalMethodContext: "",
    ResultAnalyticalMethodID: "",
    ResultAnalyticalMethodName: "",
    ResultComment: "Tmoy journalier/daily Tmean",
    ResultDetectionCondition: "",
    ResultDetectionQuantitationLimitMeasure: "",
    ResultDetectionQuantitationLimitType: "",
    ResultDetectionQuantitationLimitUnit: "",
    ResultSampleFraction: "",
    ResultStatusID: "",
    ResultUnit: "deg C",
    ResultValue: "18.5",
    ResultValueType: "Calculated",
    SampleCollectionEquipmentName: "",
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockNonWaterTempRow = {
  data: {
    ActivityDepthHeightMeasure: "",
    ActivityDepthHeightUnit: "",
    ActivityEndDate: "",
    ActivityEndTime: "",
    ActivityMediaName: "Surface Water",
    ActivityStartDate: "2013-09-26",
    ActivityStartTime: "10:35:00",
    ActivityType: "Field Msr/Obs-Portable Data Logger",
    AnalysisStartDate: "",
    AnalysisStartTime: "",
    AnalysisStartTimeZone: "",
    CharacteristicName: "Dissolved oxygen (DO)", // Not water temperature
    DatasetName: "Indian Bay Ecosystem Corporation",
    LaboratoryName: "",
    LaboratorySampleID: "",
    MethodSpeciation: "",
    MonitoringLocationHorizontalAccuracyMeasure: "",
    MonitoringLocationHorizontalAccuracyUnit: "",
    MonitoringLocationHorizontalCoordinateReferenceSystem: "UNKWN",
    MonitoringLocationID: "WS",
    MonitoringLocationLatitude: "49.01661",
    MonitoringLocationLongitude: "-53.86382",
    MonitoringLocationName: "Wareham Spring",
    MonitoringLocationType: "River/Stream",
    MonitoringLocationVerticalMeasure: "",
    MonitoringLocationVerticalUnit: "",
    ResultAnalyticalMethodContext: "",
    ResultAnalyticalMethodID: "",
    ResultAnalyticalMethodName: "",
    ResultComment: "",
    ResultDetectionCondition: "",
    ResultDetectionQuantitationLimitMeasure: "",
    ResultDetectionQuantitationLimitType: "",
    ResultDetectionQuantitationLimitUnit: "",
    ResultSampleFraction: "",
    ResultStatusID: "",
    ResultUnit: "mg/L",
    ResultValue: "7.2",
    ResultValueType: "",
    SampleCollectionEquipmentName: "",
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockInvalidRow = {
  data: null, // This will cause an error during processing
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockRowWithMissingLocation = {
  data: {
    CharacteristicName: "Temperature, water",
    ResultUnit: "deg C",
    ResultValue: "16.2",
    // Missing MonitoringLocationID field
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};

export const mockRowWithMissingResultFields = {
  data: {
    MonitoringLocationID: "TEST-LOC-001",
    CharacteristicName: "Temperature, water",
    // Missing ResultValue and ResultUnit fields
  },
  errors: [],
  meta: {
    delimiter: ",",
    linebreak: "\n",
    aborted: false,
    truncated: false,
    cursor: 0,
  },
};
